on:
  push:
  pull_request:
name: build
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install bats golang make openssl swtpm tpm2-tools qemu-kvm
      - name: build
        run: |
          make
      - name: test
        run: |
          make test
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: trust
